// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "array_sum.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic array_sum::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic array_sum::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<34> array_sum::ap_ST_st1_fsm_0 = "1";
const sc_lv<34> array_sum::ap_ST_st2_fsm_1 = "10";
const sc_lv<34> array_sum::ap_ST_st3_fsm_2 = "100";
const sc_lv<34> array_sum::ap_ST_st4_fsm_3 = "1000";
const sc_lv<34> array_sum::ap_ST_st5_fsm_4 = "10000";
const sc_lv<34> array_sum::ap_ST_st6_fsm_5 = "100000";
const sc_lv<34> array_sum::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<34> array_sum::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<34> array_sum::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<34> array_sum::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<34> array_sum::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<34> array_sum::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<34> array_sum::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<34> array_sum::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<34> array_sum::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<34> array_sum::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<34> array_sum::ap_ST_st17_fsm_16 = "10000000000000000";
const sc_lv<34> array_sum::ap_ST_st18_fsm_17 = "100000000000000000";
const sc_lv<34> array_sum::ap_ST_st19_fsm_18 = "1000000000000000000";
const sc_lv<34> array_sum::ap_ST_st20_fsm_19 = "10000000000000000000";
const sc_lv<34> array_sum::ap_ST_st21_fsm_20 = "100000000000000000000";
const sc_lv<34> array_sum::ap_ST_st22_fsm_21 = "1000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st23_fsm_22 = "10000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st24_fsm_23 = "100000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st25_fsm_24 = "1000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st26_fsm_25 = "10000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st27_fsm_26 = "100000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st28_fsm_27 = "1000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st29_fsm_28 = "10000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st30_fsm_29 = "100000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st31_fsm_30 = "1000000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st32_fsm_31 = "10000000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st33_fsm_32 = "100000000000000000000000000000000";
const sc_lv<34> array_sum::ap_ST_st34_fsm_33 = "1000000000000000000000000000000000";
const sc_lv<32> array_sum::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> array_sum::ap_const_lv1_1 = "1";
const sc_lv<32> array_sum::ap_const_lv32_1 = "1";
const sc_lv<32> array_sum::ap_const_lv32_3 = "11";
const sc_lv<32> array_sum::ap_const_lv32_7 = "111";
const sc_lv<32> array_sum::ap_const_lv32_9 = "1001";
const sc_lv<32> array_sum::ap_const_lv32_B = "1011";
const sc_lv<32> array_sum::ap_const_lv32_F = "1111";
const sc_lv<32> array_sum::ap_const_lv32_13 = "10011";
const sc_lv<32> array_sum::ap_const_lv32_17 = "10111";
const sc_lv<32> array_sum::ap_const_lv32_19 = "11001";
const sc_lv<32> array_sum::ap_const_lv32_1B = "11011";
const sc_lv<32> array_sum::ap_const_lv32_1F = "11111";
const sc_lv<32> array_sum::ap_const_lv32_5 = "101";
const sc_lv<32> array_sum::ap_const_lv32_D = "1101";
const sc_lv<32> array_sum::ap_const_lv32_11 = "10001";
const sc_lv<32> array_sum::ap_const_lv32_15 = "10101";
const sc_lv<32> array_sum::ap_const_lv32_1D = "11101";
const sc_lv<32> array_sum::ap_const_lv32_6 = "110";
const sc_lv<32> array_sum::ap_const_lv32_E = "1110";
const sc_lv<32> array_sum::ap_const_lv32_12 = "10010";
const sc_lv<32> array_sum::ap_const_lv32_16 = "10110";
const sc_lv<32> array_sum::ap_const_lv32_1E = "11110";
const sc_lv<32> array_sum::ap_const_lv32_2 = "10";
const sc_lv<32> array_sum::ap_const_lv32_A = "1010";
const sc_lv<32> array_sum::ap_const_lv32_1A = "11010";
const sc_lv<32> array_sum::ap_const_lv32_4 = "100";
const sc_lv<32> array_sum::ap_const_lv32_C = "1100";
const sc_lv<32> array_sum::ap_const_lv32_1C = "11100";
const sc_lv<32> array_sum::ap_const_lv32_8 = "1000";
const sc_lv<32> array_sum::ap_const_lv32_10 = "10000";
const sc_lv<32> array_sum::ap_const_lv32_14 = "10100";
const sc_lv<32> array_sum::ap_const_lv32_18 = "11000";
const sc_lv<32> array_sum::ap_const_lv32_20 = "100000";
const sc_lv<64> array_sum::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> array_sum::ap_const_lv64_1 = "1";
const sc_lv<64> array_sum::ap_const_lv64_2 = "10";
const sc_lv<64> array_sum::ap_const_lv64_3 = "11";
const sc_lv<64> array_sum::ap_const_lv64_4 = "100";
const sc_lv<64> array_sum::ap_const_lv64_5 = "101";
const sc_lv<64> array_sum::ap_const_lv64_6 = "110";
const sc_lv<64> array_sum::ap_const_lv64_7 = "111";
const sc_lv<64> array_sum::ap_const_lv64_8 = "1000";
const sc_lv<64> array_sum::ap_const_lv64_9 = "1001";
const sc_lv<64> array_sum::ap_const_lv64_A = "1010";
const sc_lv<64> array_sum::ap_const_lv64_B = "1011";
const sc_lv<64> array_sum::ap_const_lv64_C = "1100";
const sc_lv<64> array_sum::ap_const_lv64_D = "1101";
const sc_lv<64> array_sum::ap_const_lv64_E = "1110";
const sc_lv<64> array_sum::ap_const_lv64_F = "1111";
const sc_lv<64> array_sum::ap_const_lv64_10 = "10000";
const sc_lv<64> array_sum::ap_const_lv64_11 = "10001";
const sc_lv<64> array_sum::ap_const_lv64_12 = "10010";
const sc_lv<64> array_sum::ap_const_lv64_13 = "10011";
const sc_lv<64> array_sum::ap_const_lv64_14 = "10100";
const sc_lv<64> array_sum::ap_const_lv64_15 = "10101";
const sc_lv<64> array_sum::ap_const_lv64_16 = "10110";
const sc_lv<64> array_sum::ap_const_lv64_17 = "10111";
const sc_lv<64> array_sum::ap_const_lv64_18 = "11000";
const sc_lv<64> array_sum::ap_const_lv64_19 = "11001";
const sc_lv<64> array_sum::ap_const_lv64_1A = "11010";
const sc_lv<64> array_sum::ap_const_lv64_1B = "11011";
const sc_lv<64> array_sum::ap_const_lv64_1C = "11100";
const sc_lv<64> array_sum::ap_const_lv64_1D = "11101";
const sc_lv<64> array_sum::ap_const_lv64_1E = "11110";
const sc_lv<64> array_sum::ap_const_lv64_1F = "11111";
const sc_lv<64> array_sum::ap_const_lv64_20 = "100000";
const sc_lv<64> array_sum::ap_const_lv64_21 = "100001";
const sc_lv<64> array_sum::ap_const_lv64_22 = "100010";
const sc_lv<64> array_sum::ap_const_lv64_23 = "100011";
const sc_lv<64> array_sum::ap_const_lv64_24 = "100100";
const sc_lv<64> array_sum::ap_const_lv64_25 = "100101";
const sc_lv<64> array_sum::ap_const_lv64_26 = "100110";
const sc_lv<64> array_sum::ap_const_lv64_27 = "100111";
const sc_lv<64> array_sum::ap_const_lv64_28 = "101000";
const sc_lv<64> array_sum::ap_const_lv64_29 = "101001";
const sc_lv<64> array_sum::ap_const_lv64_2A = "101010";
const sc_lv<64> array_sum::ap_const_lv64_2B = "101011";
const sc_lv<64> array_sum::ap_const_lv64_2C = "101100";
const sc_lv<64> array_sum::ap_const_lv64_2D = "101101";
const sc_lv<64> array_sum::ap_const_lv64_2E = "101110";
const sc_lv<64> array_sum::ap_const_lv64_2F = "101111";
const sc_lv<64> array_sum::ap_const_lv64_30 = "110000";
const sc_lv<64> array_sum::ap_const_lv64_31 = "110001";
const sc_lv<64> array_sum::ap_const_lv64_32 = "110010";
const sc_lv<64> array_sum::ap_const_lv64_33 = "110011";
const sc_lv<64> array_sum::ap_const_lv64_34 = "110100";
const sc_lv<64> array_sum::ap_const_lv64_35 = "110101";
const sc_lv<64> array_sum::ap_const_lv64_36 = "110110";
const sc_lv<64> array_sum::ap_const_lv64_37 = "110111";
const sc_lv<64> array_sum::ap_const_lv64_38 = "111000";
const sc_lv<64> array_sum::ap_const_lv64_39 = "111001";
const sc_lv<64> array_sum::ap_const_lv64_3A = "111010";
const sc_lv<64> array_sum::ap_const_lv64_3B = "111011";
const sc_lv<64> array_sum::ap_const_lv64_3C = "111100";
const sc_lv<64> array_sum::ap_const_lv64_3D = "111101";
const sc_lv<64> array_sum::ap_const_lv64_3E = "111110";
const sc_lv<64> array_sum::ap_const_lv64_3F = "111111";
const sc_lv<32> array_sum::ap_const_lv32_21 = "100001";

array_sum::array_sum(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_sig_cseq_ST_st34_fsm_33 );
    sensitive << ( tmp31_fu_797_p2 );
    sensitive << ( tmp_fu_789_p2 );

    SC_METHOD(thread_ap_sig_bdd_105);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_113);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_121);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_129);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_137);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_145);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_164);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_171);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_179);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_187);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_195);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_204);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_211);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_219);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_227);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_235);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_245);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_252);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_260);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_269);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_276);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_284);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_329);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_370);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_394);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_419);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_458);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_613);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_74);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_81);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_89);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_97);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_97 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_252 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_105 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_bdd_276 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_bdd_171 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_bdd_211 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_bdd_113 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_16);
    sensitive << ( ap_sig_bdd_370 );

    SC_METHOD(thread_ap_sig_cseq_ST_st18_fsm_17);
    sensitive << ( ap_sig_bdd_179 );

    SC_METHOD(thread_ap_sig_cseq_ST_st19_fsm_18);
    sensitive << ( ap_sig_bdd_219 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_50 );

    SC_METHOD(thread_ap_sig_cseq_ST_st20_fsm_19);
    sensitive << ( ap_sig_bdd_121 );

    SC_METHOD(thread_ap_sig_cseq_ST_st21_fsm_20);
    sensitive << ( ap_sig_bdd_394 );

    SC_METHOD(thread_ap_sig_cseq_ST_st22_fsm_21);
    sensitive << ( ap_sig_bdd_187 );

    SC_METHOD(thread_ap_sig_cseq_ST_st23_fsm_22);
    sensitive << ( ap_sig_bdd_227 );

    SC_METHOD(thread_ap_sig_cseq_ST_st24_fsm_23);
    sensitive << ( ap_sig_bdd_129 );

    SC_METHOD(thread_ap_sig_cseq_ST_st25_fsm_24);
    sensitive << ( ap_sig_bdd_419 );

    SC_METHOD(thread_ap_sig_cseq_ST_st26_fsm_25);
    sensitive << ( ap_sig_bdd_137 );

    SC_METHOD(thread_ap_sig_cseq_ST_st27_fsm_26);
    sensitive << ( ap_sig_bdd_260 );

    SC_METHOD(thread_ap_sig_cseq_ST_st28_fsm_27);
    sensitive << ( ap_sig_bdd_145 );

    SC_METHOD(thread_ap_sig_cseq_ST_st29_fsm_28);
    sensitive << ( ap_sig_bdd_284 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_74 );

    SC_METHOD(thread_ap_sig_cseq_ST_st30_fsm_29);
    sensitive << ( ap_sig_bdd_195 );

    SC_METHOD(thread_ap_sig_cseq_ST_st31_fsm_30);
    sensitive << ( ap_sig_bdd_235 );

    SC_METHOD(thread_ap_sig_cseq_ST_st32_fsm_31);
    sensitive << ( ap_sig_bdd_153 );

    SC_METHOD(thread_ap_sig_cseq_ST_st33_fsm_32);
    sensitive << ( ap_sig_bdd_458 );

    SC_METHOD(thread_ap_sig_cseq_ST_st34_fsm_33);
    sensitive << ( ap_sig_bdd_613 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_245 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_81 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_269 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_164 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_204 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_89 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_329 );

    SC_METHOD(thread_array_r_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );
    sensitive << ( ap_sig_cseq_ST_st28_fsm_27 );
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st27_fsm_26 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st29_fsm_28 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_array_r_address1);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );
    sensitive << ( ap_sig_cseq_ST_st28_fsm_27 );
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st27_fsm_26 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st29_fsm_28 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_array_r_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );
    sensitive << ( ap_sig_cseq_ST_st28_fsm_27 );
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st27_fsm_26 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st29_fsm_28 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_array_r_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st20_fsm_19 );
    sensitive << ( ap_sig_cseq_ST_st24_fsm_23 );
    sensitive << ( ap_sig_cseq_ST_st26_fsm_25 );
    sensitive << ( ap_sig_cseq_ST_st28_fsm_27 );
    sensitive << ( ap_sig_cseq_ST_st32_fsm_31 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st18_fsm_17 );
    sensitive << ( ap_sig_cseq_ST_st22_fsm_21 );
    sensitive << ( ap_sig_cseq_ST_st30_fsm_29 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );
    sensitive << ( ap_sig_cseq_ST_st19_fsm_18 );
    sensitive << ( ap_sig_cseq_ST_st23_fsm_22 );
    sensitive << ( ap_sig_cseq_ST_st31_fsm_30 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st27_fsm_26 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st29_fsm_28 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st17_fsm_16 );
    sensitive << ( ap_sig_cseq_ST_st21_fsm_20 );
    sensitive << ( ap_sig_cseq_ST_st25_fsm_24 );

    SC_METHOD(thread_grp_fu_723_p2);
    sensitive << ( array_r_q0 );
    sensitive << ( array_r_q1 );

    SC_METHOD(thread_grp_fu_745_p2);
    sensitive << ( reg_729 );
    sensitive << ( reg_733 );

    SC_METHOD(thread_grp_fu_751_p2);
    sensitive << ( grp_fu_723_p2 );
    sensitive << ( grp_fu_745_p2 );

    SC_METHOD(thread_grp_fu_757_p2);
    sensitive << ( reg_737 );
    sensitive << ( reg_741 );

    SC_METHOD(thread_grp_fu_763_p2);
    sensitive << ( grp_fu_751_p2 );
    sensitive << ( grp_fu_757_p2 );

    SC_METHOD(thread_grp_fu_777_p2);
    sensitive << ( reg_769 );
    sensitive << ( reg_773 );

    SC_METHOD(thread_grp_fu_783_p2);
    sensitive << ( grp_fu_763_p2 );
    sensitive << ( grp_fu_777_p2 );

    SC_METHOD(thread_tmp31_fu_797_p2);
    sensitive << ( tmp47_reg_1148 );
    sensitive << ( tmp32_fu_793_p2 );

    SC_METHOD(thread_tmp32_fu_793_p2);
    sensitive << ( tmp33_reg_1028 );
    sensitive << ( tmp40_reg_1073 );

    SC_METHOD(thread_tmp_fu_789_p2);
    sensitive << ( tmp1_reg_898 );
    sensitive << ( tmp16_reg_983 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "array_sum_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, array_r_address0, "(port)array_r_address0");
    sc_trace(mVcdFile, array_r_ce0, "(port)array_r_ce0");
    sc_trace(mVcdFile, array_r_q0, "(port)array_r_q0");
    sc_trace(mVcdFile, array_r_address1, "(port)array_r_address1");
    sc_trace(mVcdFile, array_r_ce1, "(port)array_r_ce1");
    sc_trace(mVcdFile, array_r_q1, "(port)array_r_q1");
    sc_trace(mVcdFile, length_r, "(port)length_r");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_50, "ap_sig_bdd_50");
    sc_trace(mVcdFile, reg_729, "reg_729");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_74, "ap_sig_bdd_74");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_81, "ap_sig_bdd_81");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_89, "ap_sig_bdd_89");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_97, "ap_sig_bdd_97");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_105, "ap_sig_bdd_105");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_bdd_113, "ap_sig_bdd_113");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st20_fsm_19, "ap_sig_cseq_ST_st20_fsm_19");
    sc_trace(mVcdFile, ap_sig_bdd_121, "ap_sig_bdd_121");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st24_fsm_23, "ap_sig_cseq_ST_st24_fsm_23");
    sc_trace(mVcdFile, ap_sig_bdd_129, "ap_sig_bdd_129");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st26_fsm_25, "ap_sig_cseq_ST_st26_fsm_25");
    sc_trace(mVcdFile, ap_sig_bdd_137, "ap_sig_bdd_137");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st28_fsm_27, "ap_sig_cseq_ST_st28_fsm_27");
    sc_trace(mVcdFile, ap_sig_bdd_145, "ap_sig_bdd_145");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st32_fsm_31, "ap_sig_cseq_ST_st32_fsm_31");
    sc_trace(mVcdFile, ap_sig_bdd_153, "ap_sig_bdd_153");
    sc_trace(mVcdFile, reg_733, "reg_733");
    sc_trace(mVcdFile, grp_fu_723_p2, "grp_fu_723_p2");
    sc_trace(mVcdFile, reg_737, "reg_737");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_164, "ap_sig_bdd_164");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_bdd_171, "ap_sig_bdd_171");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st18_fsm_17, "ap_sig_cseq_ST_st18_fsm_17");
    sc_trace(mVcdFile, ap_sig_bdd_179, "ap_sig_bdd_179");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st22_fsm_21, "ap_sig_cseq_ST_st22_fsm_21");
    sc_trace(mVcdFile, ap_sig_bdd_187, "ap_sig_bdd_187");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st30_fsm_29, "ap_sig_cseq_ST_st30_fsm_29");
    sc_trace(mVcdFile, ap_sig_bdd_195, "ap_sig_bdd_195");
    sc_trace(mVcdFile, reg_741, "reg_741");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_204, "ap_sig_bdd_204");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_bdd_211, "ap_sig_bdd_211");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st19_fsm_18, "ap_sig_cseq_ST_st19_fsm_18");
    sc_trace(mVcdFile, ap_sig_bdd_219, "ap_sig_bdd_219");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st23_fsm_22, "ap_sig_cseq_ST_st23_fsm_22");
    sc_trace(mVcdFile, ap_sig_bdd_227, "ap_sig_bdd_227");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st31_fsm_30, "ap_sig_cseq_ST_st31_fsm_30");
    sc_trace(mVcdFile, ap_sig_bdd_235, "ap_sig_bdd_235");
    sc_trace(mVcdFile, grp_fu_751_p2, "grp_fu_751_p2");
    sc_trace(mVcdFile, reg_769, "reg_769");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_245, "ap_sig_bdd_245");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_252, "ap_sig_bdd_252");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st27_fsm_26, "ap_sig_cseq_ST_st27_fsm_26");
    sc_trace(mVcdFile, ap_sig_bdd_260, "ap_sig_bdd_260");
    sc_trace(mVcdFile, reg_773, "reg_773");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_269, "ap_sig_bdd_269");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_bdd_276, "ap_sig_bdd_276");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st29_fsm_28, "ap_sig_cseq_ST_st29_fsm_28");
    sc_trace(mVcdFile, ap_sig_bdd_284, "ap_sig_bdd_284");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_329, "ap_sig_bdd_329");
    sc_trace(mVcdFile, grp_fu_783_p2, "grp_fu_783_p2");
    sc_trace(mVcdFile, tmp1_reg_898, "tmp1_reg_898");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_16, "ap_sig_cseq_ST_st17_fsm_16");
    sc_trace(mVcdFile, ap_sig_bdd_370, "ap_sig_bdd_370");
    sc_trace(mVcdFile, tmp16_reg_983, "tmp16_reg_983");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st21_fsm_20, "ap_sig_cseq_ST_st21_fsm_20");
    sc_trace(mVcdFile, ap_sig_bdd_394, "ap_sig_bdd_394");
    sc_trace(mVcdFile, grp_fu_763_p2, "grp_fu_763_p2");
    sc_trace(mVcdFile, tmp33_reg_1028, "tmp33_reg_1028");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st25_fsm_24, "ap_sig_cseq_ST_st25_fsm_24");
    sc_trace(mVcdFile, ap_sig_bdd_419, "ap_sig_bdd_419");
    sc_trace(mVcdFile, tmp40_reg_1073, "tmp40_reg_1073");
    sc_trace(mVcdFile, tmp47_reg_1148, "tmp47_reg_1148");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st33_fsm_32, "ap_sig_cseq_ST_st33_fsm_32");
    sc_trace(mVcdFile, ap_sig_bdd_458, "ap_sig_bdd_458");
    sc_trace(mVcdFile, grp_fu_745_p2, "grp_fu_745_p2");
    sc_trace(mVcdFile, grp_fu_757_p2, "grp_fu_757_p2");
    sc_trace(mVcdFile, grp_fu_777_p2, "grp_fu_777_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st34_fsm_33, "ap_sig_cseq_ST_st34_fsm_33");
    sc_trace(mVcdFile, ap_sig_bdd_613, "ap_sig_bdd_613");
    sc_trace(mVcdFile, tmp32_fu_793_p2, "tmp32_fu_793_p2");
    sc_trace(mVcdFile, tmp31_fu_797_p2, "tmp31_fu_797_p2");
    sc_trace(mVcdFile, tmp_fu_789_p2, "tmp_fu_789_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("array_sum.hdltvin.dat");
    mHdltvoutHandle.open("array_sum.hdltvout.dat");
}

array_sum::~array_sum() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void array_sum::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st28_fsm_27.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read()))) {
        reg_729 = array_r_q0.read();
        reg_733 = array_r_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()))) {
        reg_737 = grp_fu_723_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()))) {
        reg_741 = grp_fu_723_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st27_fsm_26.read()))) {
        reg_769 = grp_fu_751_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st29_fsm_28.read()))) {
        reg_773 = grp_fu_751_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        tmp16_reg_983 = grp_fu_783_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        tmp1_reg_898 = grp_fu_783_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        tmp33_reg_1028 = grp_fu_763_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        tmp40_reg_1073 = grp_fu_763_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st33_fsm_32.read())) {
        tmp47_reg_1148 = grp_fu_783_p2.read();
    }
}

void array_sum::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void array_sum::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void array_sum::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st34_fsm_33.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void array_sum::thread_ap_return() {
    ap_return = (!tmp31_fu_797_p2.read().is_01() || !tmp_fu_789_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp31_fu_797_p2.read()) + sc_biguint<32>(tmp_fu_789_p2.read()));
}

void array_sum::thread_ap_sig_bdd_105() {
    ap_sig_bdd_105 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void array_sum::thread_ap_sig_bdd_113() {
    ap_sig_bdd_113 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void array_sum::thread_ap_sig_bdd_121() {
    ap_sig_bdd_121 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(19, 19));
}

void array_sum::thread_ap_sig_bdd_129() {
    ap_sig_bdd_129 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(23, 23));
}

void array_sum::thread_ap_sig_bdd_137() {
    ap_sig_bdd_137 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(25, 25));
}

void array_sum::thread_ap_sig_bdd_145() {
    ap_sig_bdd_145 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(27, 27));
}

void array_sum::thread_ap_sig_bdd_153() {
    ap_sig_bdd_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(31, 31));
}

void array_sum::thread_ap_sig_bdd_164() {
    ap_sig_bdd_164 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void array_sum::thread_ap_sig_bdd_171() {
    ap_sig_bdd_171 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void array_sum::thread_ap_sig_bdd_179() {
    ap_sig_bdd_179 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(17, 17));
}

void array_sum::thread_ap_sig_bdd_187() {
    ap_sig_bdd_187 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(21, 21));
}

void array_sum::thread_ap_sig_bdd_195() {
    ap_sig_bdd_195 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(29, 29));
}

void array_sum::thread_ap_sig_bdd_204() {
    ap_sig_bdd_204 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void array_sum::thread_ap_sig_bdd_211() {
    ap_sig_bdd_211 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void array_sum::thread_ap_sig_bdd_219() {
    ap_sig_bdd_219 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(18, 18));
}

void array_sum::thread_ap_sig_bdd_227() {
    ap_sig_bdd_227 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(22, 22));
}

void array_sum::thread_ap_sig_bdd_235() {
    ap_sig_bdd_235 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(30, 30));
}

void array_sum::thread_ap_sig_bdd_245() {
    ap_sig_bdd_245 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void array_sum::thread_ap_sig_bdd_252() {
    ap_sig_bdd_252 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void array_sum::thread_ap_sig_bdd_260() {
    ap_sig_bdd_260 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(26, 26));
}

void array_sum::thread_ap_sig_bdd_269() {
    ap_sig_bdd_269 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void array_sum::thread_ap_sig_bdd_276() {
    ap_sig_bdd_276 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void array_sum::thread_ap_sig_bdd_284() {
    ap_sig_bdd_284 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(28, 28));
}

void array_sum::thread_ap_sig_bdd_329() {
    ap_sig_bdd_329 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void array_sum::thread_ap_sig_bdd_370() {
    ap_sig_bdd_370 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(16, 16));
}

void array_sum::thread_ap_sig_bdd_394() {
    ap_sig_bdd_394 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(20, 20));
}

void array_sum::thread_ap_sig_bdd_419() {
    ap_sig_bdd_419 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(24, 24));
}

void array_sum::thread_ap_sig_bdd_458() {
    ap_sig_bdd_458 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(32, 32));
}

void array_sum::thread_ap_sig_bdd_50() {
    ap_sig_bdd_50 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void array_sum::thread_ap_sig_bdd_613() {
    ap_sig_bdd_613 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(33, 33));
}

void array_sum::thread_ap_sig_bdd_74() {
    ap_sig_bdd_74 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void array_sum::thread_ap_sig_bdd_81() {
    ap_sig_bdd_81 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void array_sum::thread_ap_sig_bdd_89() {
    ap_sig_bdd_89 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void array_sum::thread_ap_sig_bdd_97() {
    ap_sig_bdd_97 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void array_sum::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_97.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_252.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_105.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_bdd_276.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_bdd_171.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_bdd_211.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_bdd_113.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st17_fsm_16() {
    if (ap_sig_bdd_370.read()) {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st18_fsm_17() {
    if (ap_sig_bdd_179.read()) {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st19_fsm_18() {
    if (ap_sig_bdd_219.read()) {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_50.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st20_fsm_19() {
    if (ap_sig_bdd_121.read()) {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st21_fsm_20() {
    if (ap_sig_bdd_394.read()) {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st22_fsm_21() {
    if (ap_sig_bdd_187.read()) {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st23_fsm_22() {
    if (ap_sig_bdd_227.read()) {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st24_fsm_23() {
    if (ap_sig_bdd_129.read()) {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st24_fsm_23 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st25_fsm_24() {
    if (ap_sig_bdd_419.read()) {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st25_fsm_24 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st26_fsm_25() {
    if (ap_sig_bdd_137.read()) {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st26_fsm_25 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st27_fsm_26() {
    if (ap_sig_bdd_260.read()) {
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st27_fsm_26 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st28_fsm_27() {
    if (ap_sig_bdd_145.read()) {
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st28_fsm_27 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st29_fsm_28() {
    if (ap_sig_bdd_284.read()) {
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st29_fsm_28 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_74.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st30_fsm_29() {
    if (ap_sig_bdd_195.read()) {
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st30_fsm_29 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st31_fsm_30() {
    if (ap_sig_bdd_235.read()) {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st31_fsm_30 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st32_fsm_31() {
    if (ap_sig_bdd_153.read()) {
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st32_fsm_31 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st33_fsm_32() {
    if (ap_sig_bdd_458.read()) {
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st33_fsm_32 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st34_fsm_33() {
    if (ap_sig_bdd_613.read()) {
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st34_fsm_33 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_245.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_81.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_269.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_164.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_204.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_89.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void array_sum::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_329.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void array_sum::thread_array_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_3E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_3C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_3A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st29_fsm_28.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_38);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st28_fsm_27.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_36);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st27_fsm_26.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_34);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_32);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_30);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_2E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_2C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_2A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_28);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_26);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_24);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_22);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_20);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_1E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_1C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_1A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_18);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_16);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_14);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_12);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_10);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        array_r_address0 =  (sc_lv<6>) (ap_const_lv64_0);
    } else {
        array_r_address0 = "XXXXXX";
    }
}

void array_sum::thread_array_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_3F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_3D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_3B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st29_fsm_28.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_39);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st28_fsm_27.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_37);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st27_fsm_26.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_35);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_33);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_31);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_2F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_2D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_2B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_29);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_27);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_25);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_23);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_21);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_1F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_1D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_1B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_19);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_17);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_15);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_13);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_11);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        array_r_address1 =  (sc_lv<6>) (ap_const_lv64_1);
    } else {
        array_r_address1 = "XXXXXX";
    }
}

void array_sum::thread_array_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st28_fsm_27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st27_fsm_26.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st29_fsm_28.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()))) {
        array_r_ce0 = ap_const_logic_1;
    } else {
        array_r_ce0 = ap_const_logic_0;
    }
}

void array_sum::thread_array_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st20_fsm_19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st24_fsm_23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st26_fsm_25.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st28_fsm_27.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st32_fsm_31.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st18_fsm_17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st22_fsm_21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st30_fsm_29.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st19_fsm_18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st23_fsm_22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st31_fsm_30.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st27_fsm_26.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st29_fsm_28.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st21_fsm_20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st25_fsm_24.read()))) {
        array_r_ce1 = ap_const_logic_1;
    } else {
        array_r_ce1 = ap_const_logic_0;
    }
}

void array_sum::thread_grp_fu_723_p2() {
    grp_fu_723_p2 = (!array_r_q0.read().is_01() || !array_r_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(array_r_q0.read()) + sc_biguint<32>(array_r_q1.read()));
}

void array_sum::thread_grp_fu_745_p2() {
    grp_fu_745_p2 = (!reg_729.read().is_01() || !reg_733.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_729.read()) + sc_biguint<32>(reg_733.read()));
}

void array_sum::thread_grp_fu_751_p2() {
    grp_fu_751_p2 = (!grp_fu_723_p2.read().is_01() || !grp_fu_745_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(grp_fu_723_p2.read()) + sc_biguint<32>(grp_fu_745_p2.read()));
}

void array_sum::thread_grp_fu_757_p2() {
    grp_fu_757_p2 = (!reg_741.read().is_01() || !reg_737.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_741.read()) + sc_biguint<32>(reg_737.read()));
}

void array_sum::thread_grp_fu_763_p2() {
    grp_fu_763_p2 = (!grp_fu_751_p2.read().is_01() || !grp_fu_757_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(grp_fu_751_p2.read()) + sc_biguint<32>(grp_fu_757_p2.read()));
}

void array_sum::thread_grp_fu_777_p2() {
    grp_fu_777_p2 = (!reg_773.read().is_01() || !reg_769.read().is_01())? sc_lv<32>(): (sc_biguint<32>(reg_773.read()) + sc_biguint<32>(reg_769.read()));
}

void array_sum::thread_grp_fu_783_p2() {
    grp_fu_783_p2 = (!grp_fu_763_p2.read().is_01() || !grp_fu_777_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(grp_fu_763_p2.read()) + sc_biguint<32>(grp_fu_777_p2.read()));
}

void array_sum::thread_tmp31_fu_797_p2() {
    tmp31_fu_797_p2 = (!tmp47_reg_1148.read().is_01() || !tmp32_fu_793_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp47_reg_1148.read()) + sc_biguint<32>(tmp32_fu_793_p2.read()));
}

void array_sum::thread_tmp32_fu_793_p2() {
    tmp32_fu_793_p2 = (!tmp40_reg_1073.read().is_01() || !tmp33_reg_1028.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp40_reg_1073.read()) + sc_biguint<32>(tmp33_reg_1028.read()));
}

void array_sum::thread_tmp_fu_789_p2() {
    tmp_fu_789_p2 = (!tmp16_reg_983.read().is_01() || !tmp1_reg_898.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp16_reg_983.read()) + sc_biguint<32>(tmp1_reg_898.read()));
}

void array_sum::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<34>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void array_sum::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_address0\" :  \"" << array_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_ce0\" :  \"" << array_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"array_r_q0\" :  \"" << array_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_address1\" :  \"" << array_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_ce1\" :  \"" << array_r_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"array_r_q1\" :  \"" << array_r_q1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"length_r\" :  \"" << length_r.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

