#pragma line 1 "array_sum.c" ::: 0
#pragma line 1 "array_sum.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 6 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "array_sum.c" 2 ::: 192
