#pragma line 1 "array_sum.c" ::: -10
#pragma line 1 "array_sum.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2015.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "array_sum.c" 2 ::: 182
